// Airport code to city name mapping
export const AIRPORT_CITY_MAP = {
  // Canada
  YYZ: 'Toronto',
  YUL: 'Montreal',
  YVR: 'Vancouver',
  YYC: 'Calgary',
  YEG: 'Edmonton',
  YOW: 'Ottawa',
  YHZ: 'Halifax',
  YQB: 'Quebec City',
  YQM: 'Moncton',
  YWG: 'Winnipeg',
  YYJ: 'Victoria',
  YXE: 'Saskatoon',
  YQR: 'Regina',
  YYT: "St. John's",
  YFC: 'Fredericton',
  YSJ: 'Saint John',
  YZV: 'Sept-Îles',
  YUY: 'Rouyn-Noranda',
  YMM: 'Fort McMurray',
  YKA: 'Kamloops',
  YLW: 'Kelowna',
  YPR: 'Prince Rupert',
  YXY: 'Whitehorse',
  YZF: 'Yellowknife',
  YFB: 'Iqaluit',
  YGK: 'Kingston',
  YQT: 'Thunder Bay',
  YQG: 'Windsor',
  YHM: 'Hamilton',
  YXU: 'London',
  YYG: 'Charlottetown',
  YDF: 'Deer Lake',
  YJT: 'Stephenville',
  YAY: "St. Anthony",
  YYR: 'Goose Bay',
  YWK: 'Wabush',
  YVO: 'Val-d\'Or',
  YZY: 'Mackenzie',
  YZG: 'Salluit',

  // USA - Florida
  FLL: 'Fort Lauderdale',
  MCO: 'Orlando',
  MIA: 'Miami',
  TPA: 'Tampa',
  JAX: 'Jacksonville',
  RSW: 'Fort Myers',
  PBI: 'West Palm Beach',
  SRQ: 'Sarasota',
  PIE: 'St. Pete-Clearwater',
  EYW: 'Key West',

  // USA - Northeast
  JFK: 'New York (JFK)',
  LGA: 'New York (LGA)',
  EWR: 'Newark',
  BOS: 'Boston',
  PHL: 'Philadelphia',
  DCA: 'Washington DC',
  IAD: 'Washington Dulles',
  BWI: 'Baltimore',
  BDL: 'Hartford',
  PVD: 'Providence',
  BUF: 'Buffalo',
  ROC: 'Rochester',
  SYR: 'Syracuse',

  // USA - Southeast
  ATL: 'Atlanta',
  CLT: 'Charlotte',
  RDU: 'Raleigh',
  ORF: 'Norfolk',
  RIC: 'Richmond',
  GSO: 'Greensboro',
  CHS: 'Charleston',
  SAV: 'Savannah',

  // USA - Midwest
  ORD: "Chicago O'Hare",
  MDW: 'Chicago Midway',
  DTW: 'Detroit',
  MSP: 'Minneapolis',
  MSN: 'Madison',
  MKE: 'Milwaukee',
  CLE: 'Cleveland',
  CMH: 'Columbus',
  IND: 'Indianapolis',
  STL: 'St. Louis',
  MCI: 'Kansas City',
  DSM: 'Des Moines',
  OMA: 'Omaha',

  // USA - South/Texas
  DFW: 'Dallas-Fort Worth',
  IAH: 'Houston',
  HOU: 'Houston Hobby',
  AUS: 'Austin',
  SAT: 'San Antonio',
  MSY: 'New Orleans',
  MEM: 'Memphis',
  BNA: 'Nashville',
  BHM: 'Birmingham',
  LIT: 'Little Rock',
  OKC: 'Oklahoma City',
  TUL: 'Tulsa',

  // USA - Mountain West
  DEN: 'Denver',
  SLC: 'Salt Lake City',
  PHX: 'Phoenix',
  TUS: 'Tucson',
  ABQ: 'Albuquerque',
  BOI: 'Boise',
  RNO: 'Reno',
  LAS: 'Las Vegas',

  // USA - West Coast
  LAX: 'Los Angeles',
  SFO: 'San Francisco',
  SJC: 'San Jose',
  OAK: 'Oakland',
  SEA: 'Seattle',
  PDX: 'Portland',
  SAN: 'San Diego',
  SMF: 'Sacramento',
  BUR: 'Burbank',
  LGB: 'Long Beach',
  SNA: 'Orange County',

  // USA - Hawaii/Alaska
  HNL: 'Honolulu',
  OGG: 'Maui',
  KOA: 'Kona',
  LIH: 'Kauai',
  ANC: 'Anchorage',
  FAI: 'Fairbanks',

  // Mexico & Caribbean
  MEX: 'Mexico City',
  CUN: 'Cancun',
  PVR: 'Puerto Vallarta',
  SJD: 'Los Cabos',
  GDL: 'Guadalajara',
  MTY: 'Monterrey',
  NAS: 'Nassau',
  PLS: 'Providenciales',
  MBJ: 'Montego Bay',
  KIN: 'Kingston',
  SJU: 'San Juan',
  STT: 'St. Thomas',
  ANU: 'Antigua',
  UVF: 'St. Lucia',
  BGI: 'Barbados',
  POS: 'Port of Spain',
  GND: 'Grenada',
  SKB: 'St. Kitts',
  SVD: 'St. Vincent',
  GCM: 'Grand Cayman',
  SDQ: 'Santo Domingo',
  PUJ: 'Punta Cana',
  HAV: 'Havana',
  VRA: 'Varadero',
  HOG: 'Holguín',

  // Central & South America
  BOG: 'Bogotá',
  LIM: 'Lima',
  GRU: 'São Paulo',
  GIG: 'Rio de Janeiro',
  EZE: 'Buenos Aires',
  SCL: 'Santiago',
  CCS: 'Caracas',
  PTY: 'Panama City',
  SAL: 'San Salvador',
  GUA: 'Guatemala City',

  // UK & Ireland
  LHR: 'London Heathrow',
  LGW: 'London Gatwick',
  STN: 'London Stansted',
  MAN: 'Manchester',
  EDI: 'Edinburgh',
  DUB: 'Dublin',
  BHX: 'Birmingham',
  GLA: 'Glasgow',
  BRS: 'Bristol',

  // Europe
  CDG: 'Paris',
  ORY: 'Paris Orly',
  FRA: 'Frankfurt',
  MUC: 'Munich',
  AMS: 'Amsterdam',
  MAD: 'Madrid',
  BCN: 'Barcelona',
  FCO: 'Rome',
  MXP: 'Milan',
  ZRH: 'Zurich',
  GVA: 'Geneva',
  VIE: 'Vienna',
  BRU: 'Brussels',
  CPH: 'Copenhagen',
  OSL: 'Oslo',
  ARN: 'Stockholm',
  HEL: 'Helsinki',
  LIS: 'Lisbon',
  ATH: 'Athens',
  IST: 'Istanbul',

  // Middle East & Africa
  DXB: 'Dubai',
  AUH: 'Abu Dhabi',
  DOH: 'Doha',
  KWI: 'Kuwait City',
  BAH: 'Bahrain',
  AMM: 'Amman',
  TLV: 'Tel Aviv',
  CAI: 'Cairo',
  CMN: 'Casablanca',
  JNB: 'Johannesburg',
  CPT: 'Cape Town',
  NBO: 'Nairobi',
  ADD: 'Addis Ababa',

  // Asia-Pacific
  NRT: 'Tokyo',
  HND: 'Tokyo Haneda',
  KIX: 'Osaka',
  ICN: 'Seoul',
  PEK: 'Beijing',
  PVG: 'Shanghai',
  HKG: 'Hong Kong',
  SIN: 'Singapore',
  BKK: 'Bangkok',
  KUL: 'Kuala Lumpur',
  MNL: 'Manila',
  CGK: 'Jakarta',
  DEL: 'Delhi',
  BOM: 'Mumbai',
  SYD: 'Sydney',
  MEL: 'Melbourne',
  BNE: 'Brisbane',
  PER: 'Perth',
  AKL: 'Auckland',
};

export function airportToCity(code) {
  if (!code) return code;
  const upper = code.toUpperCase().trim();
  return AIRPORT_CITY_MAP[upper] || upper;
}

export function formatRoute(airports) {
  return airports.map(a => airportToCity(a)).join(' → ');
}
